language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.3
  - 1.4
otp_release:
  # - 17.5
  # - 18.0
  # - 18.1
  # - 18.2
  # - 18.3
  # - 19.0
  - 19.1

# matrix:
#   include:
#     - elixir: 1.2.5
#       otp_release: 18.3
#     - elixir: 1.3.0
#       otp_release: 19.0
#     - elixir: 1.3.1
#       otp_release: 19.0
#     - elixir: 1.3.2
#       otp_release: 19.0
#     - elixir: 1.3.4
#       otp_release: 19.1
